# Catppuccin Mocha, pulled in as a git submodule (see repo README for setup)
include ../nvim/themes/catppuccin/themes/mocha.conf


# fonts
font_family      FiraCode Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

allow_remote_control yes
listen_on unix:@kitty

# window
window_padding_width 12
confirm_os_window_close 0

# visual
background_opacity 1

# tab bar
tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1
hide_window_decorations yes 
